### ISSUE TITLE
azure doesnt work

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/gptscript#104]
See this internal slack thread: https://acorn-io.slack.com/archives/C03FU91U4SX/p1709309998579649

And this discord thread: https://discord.com/channels/1204558420984864829/1204558424734437438/1213154452744314890

And this hacky fix: https://github.com/gptscript-ai/gptscript/pull/103

I don't like the hacky fix though. Seems brittle. Also, seems like a user should not need to set the --default-model flag if they are also setting these azure env vars

**Comment by sirredbeard** [comment]
See also https://github.com/gptscript-ai/gptscript/issues/59

**Comment by keyallis** [comment]
Closing in favor of #43 for tracking purposes
