### ISSUE TITLE
Story-book example sometimes fails to create `pages` directory resulting in the illustration and story not being saved.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#130]
gptscript version - v0.0.0-dev-4909c513-dirty

**Steps to reproduce the problem:**
1. Clone https://github.com/gptscript-ai/gptscript/
2. Make a change in `examples/story-book/story-book.gpt` for  tool `story-illustrator` to point to repo -`tools: github.com/gptscript-ai/image-generation`
3.  Run gptscript  `story-book.gpt`, from `examples/story-book/` dir.
4. Script fails to create `pages` directory , resulting in no  illustration and story not being saved.
```
14:04:36 download [https://oaidalleapiprodscus.blob.core.windows.net/private/org-UZ21HIS1j93qUiZVWBOGePHu/user-nfhF7kaasrYgX69n1He52KF9/img-YHduqSS5E4aBA7XG1MONy6pa.png?rscd=inline&rsct=image%2Fpng&se=2024-03-07T23%3A03%3A45Z&sig=8H6%2BTztnOeEAZb4EKrlqq9%2B4w2%2BDQKhj4bVQ02QEHMw%3D&ske=2024-03-08T18%3A17%3A24Z&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sks=b&skt=2024-03-07T18%3A17%3A24Z&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skv=2021-08-06&sp=r&sr=b&st=2024-03-07T21%3A03%3A45Z&sv=2021-08-06] to [pages/3.png]
14:04:36 download [https://oaidalleapiprodscus.blob.core.windows.net/private/org-UZ21HIS1j93qUiZVWBOGePHu/user-nfhF7kaasrYgX69n1He52KF9/img-3RybU4zqbUn8AMsSLXIfvRrP.png?rscd=inline&rsct=image%2Fpng&se=2024-03-07T23%3A03%3A46Z&sig=FVjxvA8WBTsU32xDefBy5iNcKetmRjZAaeWaxiOeR1A%3D&ske=2024-03-08T18%3A16%3A49Z&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sks=b&skt=2024-03-07T18%3A16%3A49Z&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skv=2021-08-06&sp=r&sr=b&st=2024-03-07T21%3A03%3A46Z&sv=2021-08-06] to [pages/2.png]
14:04:36 download [https://oaidalleapiprodscus.blob.core.windows.net/private/org-UZ21HIS1j93qUiZVWBOGePHu/user-nfhF7kaasrYgX69n1He52KF9/img-3pjK1Q8Obt2WD2T2QrHv4gb1.png?rscd=inline&rsct=image%2Fpng&se=2024-03-07T23%3A03%3A48Z&sig=FQRrKWjgXHXZGlDINVAVLbjVff1WRg5lJCOKNcdUZFw%3D&ske=2024-03-08T18%3A15%3A09Z&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sks=b&skt=2024-03-07T18%3A15%3A09Z&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skv=2021-08-06&sp=r&sr=b&st=2024-03-07T21%3A03%3A48Z&sv=2021-08-06] to [pages/1.png]
2024/03/07 14:04:42 failed to create [pages/3.png]: open pages/3.png: no such file or directory
```

```
ls -ltr
total 32
-rw-r--r--  1 sangeethahariharan  staff  2186 Mar  6 13:38 README.md
-rw-r--r--  1 sangeethahariharan  staff  2405 Mar  7 10:16 story-book.gpt
-rw-r--r--@ 1 sangeethahariharan  staff  4307 Mar  7 10:36 index.html
```

**Comment by sangee2004** [comment]
I was able to reproduce this issue multiple times following these steps:

1. Delete all existing entries from existing cache repo dir -(~/Library/Caches/gptscript/repos) .
2. Make a change in `examples/story-book/story-book.gpt` for tool `story-illustrator` to point to repo - `tools: github.com/gptscript-ai/image-generation`
3. Run gptscript `story-book.gpt` from `examples/story-book/ ` dir.

 mkdir is not being called . Not sure if this is relating to tool packaging .
Running the script second time , resulted this time in mkdir being called.

**Comment by tylerslaton** [comment]
I think that this is no longer relevant now that it is a full web-app @sangee2004, if that's true could you go ahead and close this?

**Comment by njhale** [comment]
Closing this out. The story-book example has significantly changed since this issue was created. It's now a standalone app with a different architecture.
