### ISSUE TITLE
model not found: gpt-4-turbo-preview

### ISSUE THREAD

**Issue by junkistry** [gptscript-ai/gptscript#132]
Very new to AI and gptscript.I have signed up with openai API and set the API key and get the error "model not found: gpt-4-turbo-preview" when I try to run it.

Somehow the default model is getting called. What I am not able to figure out is whether a newer model has to be set in GPTScript config somewhere? Or do I need to change the default model in my openai API account?

I see that this default is set in "gptscript/pkg/openai/client.go" line 49. 
DefaultModel string         `usage:"Default LLM model to use" default:"gpt-4-turbo-preview"`

I went thru the gptscript documentation but didn't find any place to change model. How do I change this?

**Comment by ibuildthecloud** [comment]
Try `gptscript --help`

```
      --default-model string        Default LLM model to use ($GPTSCRIPT_DEFAULT_MODEL) (default "gpt-4-turbo-preview")
```

Also do `gptscript --list-models` to see which models you have available to you. I'm surprised gpt-4-turbo-preview is not there. Maybe you need to add a credit card to your account or something. I'll be curious as to why this is happening.

**Comment by junkistry** [comment]
Adding credit-card solved the issue. thank you for your suggestion.
