### ISSUE TITLE
Validation of output and retry 

### ISSUE THREAD

**Issue by ccollicutt** [gptscript-ai/gptscript#140]
Hi - First, thanks for all the work on gptscript. Amazing stuff!

I'd like to see the ability to have a validation phase, and based on the output of the validation phase, retry using the output of the validation to improve the output.

Use case:

- As someone working in Devops
- I want to have gptscript create a configuration file for me
- and I want to validate that what the LLM produces is a valid config, e.g. `sometool --validate created-config.yaml` (i.e. have a "validate" tool that runs that CLI command)
- and if that validation fails then gptscript should retry to create the requested config based on the error output provided by the validation tool, potentially trying several times

Just a thought. Thanks again!

**Comment by cjellick** [comment]
We added functionality such that if a tool exits with a non-zero exit code, the sys.error output will be sent to the LLM and the LLM will decided what to do next (which is generally retry with the additional learnings from the error messsage).

So with that I think you could write a gptscript tool to accomplish what you're describing.
