### ISSUE TITLE
Secret handling

### ISSUE THREAD

**Issue by thedadams** [gptscript-ai/gptscript#15]
I'd like to see robust secret handling incorporated into gptscript. This secret handling would take two forms:

1. A way to handle secrets for gptscripts. Environment variables are OK for local, but, even then, could be taken advantage of by a rouge script. A script would need to request and be given permission to use a secret.
2. Secret values shouldn't be sent to OpenAI.

**Comment by g-linville** [comment]
@cjellick think we can close this since we have the credentials framework now?

**Comment by thedadams** [comment]
Definitely. This was an issue I created when we were in the "play with this to see what you think" phase.
