### ISSUE TITLE
Error when running gptscript with story-book example: Executable file not found in %PATH%

### ISSUE THREAD

**Issue by chrislbrown84** [gptscript-ai/gptscript#178]
**Description:**
When attempting to run a gptscript command to generate a storybook example with specific prompts and illustrations, the process fails during the image generation phase with an error indicating that an executable file was not found in %PATH%.

**Steps to Reproduce:**

Open PowerShell as the current user.
Navigate to the project directory using cd C:\Users\XXXX\devprojects\gptscript\.
Execute the command: gptscript story-book.gpt --prompt "goldilocks" --pages 3.
The script begins execution, processing the story generation and attempting to start the image generation phase.
Error occurs during the image generation phase, specifically when attempting to execute a Python file.
Expected Behavior:
The script should complete all specified operations, including story generation and image generation, without encountering path or execution errors.

**Actual Behavior:**
The script fails during the image generation phase with the following error:

2024/03/22 22:54:25 exec: "C:\\Users\\XXXX\\AppData\\Local\\cache\\gptscript\\repos\\runtimes\\python\\4d6b72f99e8ae458c5dbf222670ab25ca0fedbd11e43f0fccf3bb46a9f966227.download\\python\\bin\\python3": executable file not found in %PATH%

**Environment:**

OS: Windows
gptscript version: [specify version if known]
Python version: [specify version if relevant]

**Comment by njhale** [comment]
Thanks for submitting this issue @chrislbrown84!

There have been some significant changes to the story book example. It's been redesigned as a standalone app to serve as a usage example for our nodejs SDK. If you're interested, you can check it out [here](https://github.com/gptscript-ai/story-book) and see if you encounter similar issues.

In the meantime I'm going to close this issue out.
