### ISSUE TITLE
--server UX is 404 page not found

### ISSUE THREAD

**Issue by kaihendry** [gptscript-ai/gptscript#190]
I raised this earlier on https://discord.com/channels/1204558420984864829/1204558424734437438/1214507757743374396

```
❯ ../gptscript --server
13:14:11 Listening on http://127.0.0.1:9090
```

![image](https://github.com/gptscript-ai/gptscript/assets/765871/e5604176-69e7-4cf3-951d-434f6d08867e)

My goal is to be able to step or tweak my prompts, not sure the UI delivers on that expectation.

**Comment by drpebcak** [comment]
The `--server` option does have a simple ui that lets you run gptscripts, but its definitely not a chatgpt-type interface like you reference on discord. The other interesting thing the `--server` option does is allow you to execute gptscripts with an http api.

Either way, the issue you reported here does not seem to be present in recent versions, so I will close this.
