### ISSUE TITLE
Provide better error message when required api key related environment variables are not present for the selected model.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#194]
gptscript version - `v0.0.0-dev-941240c5-dirty`

**Steps to reproduce the problem:**

1. Do not have ANTHROPIC_API_KEY set.
2. Try to use any claude model like `gptscript --cache=false --default-model='claude-3-opus-20240229  from github.com/gptscript-ai/claude3-openai-shim' examples/bob.gpt`
3. We see a `500 Internal Server Error` with log stack trace with following last few lines . 
```
 raise TypeError(
TypeError: "Could not resolve authentication method. Expected either api_key or auth_token to be set. Or for one of the `X-Api-Key` or `Authorization` headers to be explicitly omitted"
2024/03/27 16:23:13 error, status code: 500, message: invalid character 'I' looking for beginning of value
```

Can we provide a error message stating that ANTHROPIC_API_KEY  has be set  in this, before even attempting to do the chat completion calls ?

**Comment by sangee2004** [comment]
With latest build - `gptscript version v0.0.0-dev-5c6ff70d-dirty` , I dont see even the error message i see before 

I just see the following errors  - `status code: 500, message: Internal Server Error` which gives no indication of any errors:


```
gptscript --cache=false --default-model='claude-3-opus-20240229  from github.com/gptscript-ai/claude3-openai-shim' examples/bob.gpt
11:46:31 WARNING: Changing the default model can have unknown behavior for existing tools. Use the model field per tool instead.
11:46:31 started  [main]
11:46:31 started  [main]
11:46:31 launched [anthropic model provider][https://raw.githubusercontent.com/gptscript-ai/claude3-openai-shim/c53ba81de62e824abeede8457c84d4f79c32e6c4/tool.gpt:1] port [10861] [/usr/bin/env python3 /Users/sangeethahariharan/Library/Caches/gptscript/repos/c53ba81de62e824abeede8457c84d4f79c32e6c4/python3.12/main.py]
11:46:32 ended    [main]
11:46:32 sent     [main]
         content  [1] content | Waiting for model response...2024/04/03 11:46:32 error, status code: 500, message: Internal Server Error
```

**Comment by drpebcak** [comment]
We have done a bunch of work towards this end, so we should have better messages now when the key is unset or invalid.
