### ISSUE TITLE
Not able to direct the console output of gptscript execution into a file

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#196]
I am not able to direct the console output from gptscript execution into a file.
I tried this command and i see the gpscript execution is being halted .It may be using all the parameters after the gptscript name as input parameters?

```
gptscript --cache=false -o describe-code.gpt-gpt4.out examples/describe-code.gpt 2>&1 | tee SomeFile.txt
```

I was able to get around this problem by having the gptscrip command put into a file say `test.sh` and then using `test.sh 2>&1 | tee SomeFile.txt`

From @vincent99 :
The 2>&1 | tee ... part would be picked up by the shell and not sent to gptscript.
This sounds like the same problem Bill had with the node client where there just is no error output produced if you're not a TTY.
So you are correctly capturing the stderr output, but that output is nothing

**Comment by njhale** [comment]
Tested this on `main` (currently https://github.com/gptscript-ai/gptscript/commit/daef472ebb32664855b7bad7c32a6cbb0a3a356b) and it worked for me on zsh:

```
gptscript --disable-cache=true examples/bob-as-shell.gpt 2>&1 | tee gptscript.tee.log
```

@sangee2004 moving this over to testing for you to confirm it's no longer an issue.

**Comment by sangee2004** [comment]
Tested with gptscript version v0.9.2+0f32a9d8.

This issue is not seen anymore. Able to get output redirected to a file using the command mentioned in the issue.
