### ISSUE TITLE
How can plug AWS Bedrock into GPTScript?

### ISSUE THREAD

**Issue by csantanapr** [gptscript-ai/gptscript#200]
How can I use plug AWS Bedrock into GPTScript?

Some orgs are establised AWS Bedrock as their base for AI API serving with multiple different models. I'm interesting on how can I use GTPScript but leverage AWS Bedrock.

For example Cloude3 https://docs.aws.amazon.com/bedrock/latest/userguide/service_code_examples_bedrock-runtime_actions.html

**Comment by drpebcak** [comment]
https://docs.gptscript.ai/alternative-model-providers

For claude3 specifically, you can use the anthropic-provider https://github.com/gptscript-ai/anthropic-provider/

Your mileage may vary though - most models are not as good at function calling as gpt-4-turbo.

If you want to use some other model on bedrock, you may need to write your own provider.

**Comment by drpebcak** [comment]
If you have any additional questions about this, feel free to join our discord. There is a link to it from https://docs.gptscript.ai
