### ISSUE TITLE
Support for non-OpenAI models

### ISSUE THREAD

**Issue by chris-short** [gptscript-ai/gptscript#210]
Please consider this an umbrella issue (assuming you don't have one yet) for adding the flexibility to choose the model of the users choice.

This project is very interesting and encapsulates the hopes of GenAI for developers and non-developers alike.

But, much like many technological advances, folks are choosing what's right for their needs/desires. The answer is not always OpenAI.

I am most interested in native support for Anthropic and Ollama.

**Comment by jritsema** [comment]
This looks encouraging (tool use is now in public beta) https://docs.anthropic.com/claude/docs/tool-use

**Comment by drpebcak** [comment]
Take a look at the documentation here: https://docs.gptscript.ai/alternative-model-providers

That documentation should help you use Ollama or Claude 3, but please note that many models are not as good at function calling as gpt-4-turbo, so you may run into issues.

**Comment by drpebcak** [comment]
Also, there is a branch of the anthropic-provider that uses the beta tool use stuff - https://github.com/gptscript-ai/anthropic-provider/tree/tool-beta

**Comment by drpebcak** [comment]
The tool use stuff for anthropic is not beta anymore, and has been merged into main. I'm going to close this issue now, since we do have support for the original ask (the ability to use with other models/providers aside from openai).

**Comment by jritsema** [comment]
What is the official story for Amazon Bedrock support?  Bedrock has a new [Converse API that supports function calling (tools)](https://docs.aws.amazon.com/bedrock/latest/userguide/tool-use.html) across models.  I see this one https://github.com/gptscript-ai/claude3-bedrock-provider any idea if it uses Converse's tools?
