### ISSUE TITLE
Credentials - parsing error when running gptscript with tools that have credentials.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#237]
gptscript version v0.0.0-dev-f4284f43-dirty

**Steps to reproduce the problem:**
1. Run the following gptscript that uses a tool with credentials.

```
Tools: github.com/sangee2004/slack

search messages in slack and list all messages that have mentioned Disney in the past month
```
2. I am prompted to enter the slack token as expected and tool executes successfully.
3. Run the gptscript again.

This fails with the following parsing error:

```
09:39:34 started  [main]
09:39:35 sent     [main]
2024/04/12 09:39:35 failed to get credentials for tool slack-credential-tool: error parsing tool name and context "". Tool names cannot contain '///'
```

Note - Once I remove the `config.json` that stores the credentials , then I am able to execute the script again.

**Comment by g-linville** [comment]
@sangee2004 fix is merged

**Comment by sangee2004** [comment]
Tested with `gptscript version v0.0.0-dev-5a8a685c-dirty`

This issue is not see anymore.

When the scripts that uses  tools that have github credentials are run the second time , we are not prompted for credentials and credentials from cache gets used successfully.
