### ISSUE TITLE
Credentials - Changes to `gptscript credentials --help` and `gptscript credentials delete  --help` text.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#243]
Following are some changes that needs to be done for `gptscript credentials --help` and `gptscript credentials delete  --help` texts.

1. Hide all the `Global Flags:` presented in `gptscript credentials --help` and `gptscript credentials delete  --help` help except for `--credential-context` .

2. In the usage for `gptscript credentials delete --help` , exclude `[flags]` and include `Global Flags` before `<tool-name>`
```
Usage:
  gptscript credential delete <tool name> [flags]
```

**Comment by g-linville** [comment]
Regarding the second one of these, I don't think anything needs to change @sangee2004. The only flag to be set is `--credential-context`, and it is okay for it to come after the tool name.

**Comment by g-linville** [comment]
This should be fixed now.

**Comment by sangee2004** [comment]
Tested with `gptscript version v0.0.0-dev-656ae77b-dirty` .

This issue is addressed now.
