### ISSUE TITLE
Credentials - Do not store empty credentials.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#251]
gptscript version v0.0.0-dev-656ae77b-dirty

**Steps to reproduce the problem:**
1. Execute the following script which has a tool that has  credential tool served from gihub
```
Tools: github.com/sangee2004/slack-message/toolcred.gpt

Send a message to "sangeetest" channel saying "hello new from gptscript".
```
2. When prompted for entering the credential  - quit (clt c) or just hit enter (no credential is entered).

This results in an empty credential to be stored.

3. Execute the script again. We will not be prompted to enter the credentials and the script will fail.

**Expected Behavior:**
When user has not entered any credentials , we should not store the credentials. This way , when the script is executed the next time user will be prompted to the enter the credentials instead of failing right away.

**Note:**
Should we also consider stripping empty spaces before and after the credential string before storing and using the keys .

**Comment by g-linville** [comment]
Just merged the fix.

**Comment by sangee2004** [comment]
Tested with gptscript version v0.0.0-dev-9d41471d-dirty

Empty credentials are not stored anymore.
