### ISSUE TITLE
Credentials - Share the same credentials for image-generation and vision tools  and credentials should be able use the local env variable if set. 

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#253]
With  image-generation  tool using credentials , I am now prompted to enter OpenAI API token even when i have OPENAI_API_KEY env variable already defined and used by gptscript. In this case, we expect to be prompted for OpenAI API token  only when the env variable is not already present .

Also if vision tool also uses its own credential tool , then it would also prompt me to enter an OPENAI_API_KEY env variable even if I have set it once using image-generatiion tool. 

It would be ideal to share the same credentials for image-generation and vision tools  and for the credentials to be able use the local env variable if set.

**Comment by g-linville** [comment]
Craig asked that vision and image-gen remain separate tools. But I have added support for checking the env var. The PRs still need to be merged. I'll leave an update here when that is done.

**Comment by g-linville** [comment]
This should be good to go now.

**Comment by sangee2004** [comment]
Tested with gptscript version v0.0.0-dev-9d41471d-dirty

When `OPENAI_API_KEY`  env variable is already present , running `image-generation` and `vision` tools do not prompt for entering `tokens` as expected. Once script execution is done , checked to make sure no  `image-generation` and `vision` credentials are created as well.
