### ISSUE TITLE
github rate limit

### ISSUE THREAD

**Issue by lukemarsden** [gptscript-ai/gptscript#315]
after using gptscript for a while with github-hosted tools, I start hitting this:
```
2024/05/04 08:38:36 failed resolving github.com/gptscript-ai/search/duckduckgo at ./get-blog-posts-search.gpt: failed to GitHub commit of gptscript-ai/search at HEAD: 403 Forbidden {"message":"API rate limit exceeded for <my-ip>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```
At first I thought this was duckduckgo rate limiting me, but then I realised it was github when resolving the module itself!

Can we cache the result of whatever we're using the github API for?

**Comment by sangee2004** [comment]
One way to work around the problem is to set the following env variable - `GITHUB_AUTH_TOKEN`

**Comment by lukemarsden** [comment]
thanks! maybe add that to the readme?

**Comment by cjellick** [comment]
@sangee2004 is this in docs? could we put it in the FAQ if it isnt?

**Comment by sangee2004** [comment]
It is not currently present in our docs. I will have it added to FAQ section.

**Comment by sangee2004** [comment]
We now have documentation for handling github rate limit issue in  FAQ  section - https://github.com/gptscript-ai/gptscript/pull/646
