### ISSUE TITLE
openapi integration needs v2 support

### ISSUE THREAD

**Issue by cloudnautique** [gptscript-ai/gptscript#316]
Currently we only support Openapi v3 spec. In Python working with Flask, and anecdotally golang, it is very easy to create v2 specs, but not v3. This results in needing to use a conversion tool to get a v3 spec. If the conversion has any quirks the user will need to learn more about OpenAPI then they care to.

**Comment by g-linville** [comment]
This has been implemented in this PR: https://github.com/gptscript-ai/gptscript/pull/345
Closing.
