### ISSUE TITLE
gptscript fails to run inside containerized env's

### ISSUE THREAD

**Issue by d3287t328** [gptscript-ai/gptscript#330]
I have tested this in a fedora and ubuntu container (via toolbox and bluefin). Tool calling fails although API is set. 

```
⬢[a@toolbox agent]$ gptscript b.gpt 
19:59:35 started  [main]
19:59:37 sent     [main]
19:59:37 ended    [main]

OUTPUT:

I'm unable to perform this task.
```

```
⬢[a@toolbox agent]$ cat b.gpt 
chat: true
tools: bob

Ask Bob how he is doing and let me know exactly what he said.

---
name: bob
description: I'm Bob, a friendly guy.
args: question: The question to ask Bob.

#!/bin/bash

echo "Thanks for asking ${question}, I'm doing great fellow friendly AI tool!"
```

I am able to run the scripts just fine in wsl ubuntu. An easy way to reproduce this is to add the chat: true option to the script and you will not be given a chat shell.

**Comment by drpebcak** [comment]
I could not replicate this with 0.9.2.. using both your example script and `github.com/gptscript-ai/llm-basics-demo` I was able to chat without issues. I tried this with distrobox and toolbox. @d3287t328 can you still replicate this with the newer versions of gptscript?
