### ISSUE TITLE
support ? on user created tools

### ISSUE THREAD

**Issue by cloudnautique** [gptscript-ai/gptscript#42]
Similar to the `?` on sys.* tools allowing for the LLM to retry based on the errors, users should be able to do that with their own tools. Right now, it errors out because it can't exact match the name of tool. 

tools: mytool?

looks for a tool named `mytool?` not `mytool`.

**Comment by ibuildthecloud** [comment]
Yeah, ? only works on built in tools, that wasn't intentional but more of a bug of how I hacked in support for that. We should support it for all tool types.

**Comment by cjellick** [comment]
this happens for all tools now by default
