### ISSUE TITLE
Make default model an env var to play nice with Azure

### ISSUE THREAD

**Issue by dozsa** [gptscript-ai/gptscript#43]
I'm trying to run this on Azure and in azure the model name is not actually the model name itself, but instead a user defined model deployment name, which will be user specific. Given that model will be used for all calls, it would help to make the default model name an env var, like the other AzureAI variables. I know I can set the model name for each tool, and tested that with echo, but it is cumbersome to do that for every example and tool i run. Also i tried the hackernews example and though i set the model name for each tool, it still tried to do a call with the default model name.

**Comment by ibuildthecloud** [comment]
Yeah, this makes sense. I've never personally tried azure and the current setting that are in there I just optimistically added hoping it would make it work. We will add this too.

**Comment by keyallis** [comment]
Support should be added and verified
