### ISSUE TITLE
gptscript never stops - expected?

### ISSUE THREAD

**Issue by shuther** [gptscript-ai/gptscript#431]
Is it expected that one request sent to gptscript never ends, is it expected? is there a way to run it only once?
```
./gptscript ../examples/bob.gpt --default-model codestral --debug --debug-messages
18:13:57 started  [main] [input=--default-model codestral --debug --debug-messages]
18:13:57 sent     [main]
18:14:02 started  [bob(2)] [input={"question": "Ask how I am doing"}]
18:14:02 sent     [bob(2)]
18:14:04 ended    [bob(2)] [output=Thanks for asking \"Ask how I am doing\", I'm doing great fellow friendly AI tool!]
18:14:04 continue [main]
18:14:04 sent     [main]
18:14:09 started  [bob(3)] [input={"question": "how i am doing"}]
18:14:09 sent     [bob(3)]
18:14:11 ended    [bob(3)] [output=Thanks for asking \"how i am doing\", I'm doing great fellow friendly AI tool!]
18:14:11 continue [main]
18:14:11 sent     [main]
```

**Comment by cjellick** [comment]
hi...no that is not expected. reran a super quick test. we do not see this behavior with the default model (gpt-4o) nor mistral-large.

If it's looping like that, it is like the LLM deciding to call it again and again.

BTW, those flags you specified should be _before_ ../examples/bob.gpt. You'll get a lot more output if you move them

**Comment by cjellick** [comment]
im going to go ahead and close this issue. feel free to re-open if you need to
