### ISSUE TITLE
gemini-aistudio-provider GEMINI_API_KEY not set issue

### ISSUE THREAD

**Issue by wmashal** [gptscript-ai/gptscript#449]
Hi 

I tried to set the provider Gemini key in my docker as described in the documentation **GPTSCRIPT_PROVIDER_API_GEMINI_API_KEY** but its not working Not working, also I tried to set it with the name **GEMINI_API_KEY** without the prefix, I got the following error (What I missed)

Why provider ask to enter the key and not take it from the ENV ? (Please enter your Google AI Studio API key)

```

Error executing GPT script: Please enter your Google AI Studio API key. 
[0G[2K[1;92m? [0m[1;99mkey [0m[?25l[?25l7[999;999f[6n8[?25h[6n[?25h2024/06/05 09:16:40 EOF Failed to run sys.prompt. 09:16:40 failed to run tool [google-ai-studio-credential] 
cmd [/usr/bin/env python3 /root/.cache/gptscript/repos/bd6bbf89c7ecfd16d25c7d94dfc913b8c9e7c74a/python3.12/credential/credential.py]: exit status 1 2024/06/05 09:16:40 OPENAI_API_KEY is not set. 
Please set the OPENAI_API_KEY environment variable failed to run credential tool github.com/gptscript-ai/gemini-aistudio-provider/credential: ERROR: 
Please enter your Google AI Studio API key. [0G[2K[1;92m? [0m[1;99mkey [0m[?25l[?25l7[999;999f[6n8[?25h[6n[?25h2024/06/05 09:16:40 EOF Failed to run sys.prompt. : exit status 1

```

**Also When I tried direct on the shell with my ai studio key I got error say the key not set** 

```bash 
# gptscript script_bak.gpt
10:57:00 started  [main]
10:57:00 started  [provider: https://raw.githubusercontent.com/gptscript-ai/gemini-aistudio-provider/bd6bbf89c7ecfd16d25c7d94dfc913b8c9e7c74a/tool.gpt:Google Model Provider]
10:57:00 launched [Google Model Provider][https://raw.githubusercontent.com/gptscript-ai/gemini-aistudio-provider/bd6bbf89c7ecfd16d25c7d94dfc913b8c9e7c74a/tool.gpt:Google Model Provider] port [10832] [gptscript sys.daemon /usr/bin/env python3 /root/.cache/gptscript/repos/bd6bbf89c7ecfd16d25c7d94dfc913b8c9e7c74a/python3.12/main.py]
10:57:02 ended    [provider: https://raw.githubusercontent.com/gptscript-ai/gemini-aistudio-provider/bd6bbf89c7ecfd16d25c7d94dfc913b8c9e7c74a/tool.gpt:Google Model Provider] [output=http://127.0.0.1:10832]
10:57:02 sent     [main]
10:57:02 started  [sys.read(3)] [input={"filename": "/etc/environment"}]
10:57:02 sent     [sys.read(3)]
10:57:02 ended    [sys.read(3)] [output=The file /etc/environment has no contents]
10:57:02 continue [main]
10:57:02 sent     [main]
10:57:02 ended    [main] [output=I cannot fulfill this request. The environment variable GEMINI_API_KEY is not set.]

OUTPUT:

I cannot fulfill this request. The environment variable GEMINI_API_KEY is not set.

```

**My .gpt file**

```
tools: sys.read, sys.write, sys.exec?
Model Name: gemini-pro from github.com/gptscript-ai/gemini-aistudio-provider

Respond directly with the relevant code snippet in the appropriate language (YAML, JSON, Bash, etc.), enclosed in a code block.

What the value for GPTSCRIPT_PROVIDER_API_GEMINI_API_KEY env variable

```

**Comment by wmashal** [comment]
@g-linville any advice ?

**Comment by g-linville** [comment]
@wmashal Can you try running `gptscript credential` to list your stored credentials? See if there is one for the Gemini model provider. It is possible that it is an invalid token. You can delete a credential with `gptscript credential delete <credential name>`, and then you will be prompted to enter it again the next time you try to use the Gemini provider.

**Comment by wmashal** [comment]
> @wmashal Can you try running `gptscript credential` to list your stored credentials? See if there is one for the Gemini model provider. It is possible that it is an invalid token. You can delete a credential with `gptscript credential delete <credential name>`, and then you will be prompted to enter it again the next time you try to use the Gemini provider.

@g-linville 

No, no one for Gemini , and still ask me to prompt the openai key after I delete it. see the following screen shoots

<img width="923" alt="image" src="https://github.com/gptscript-ai/gptscript/assets/11045408/bf290fb7-fad9-47ab-b148-0afa2f0aeaca">
<img width="1563" alt="image" src="https://github.com/gptscript-ai/gptscript/assets/11045408/48017d01-1aa0-4d85-8bd7-7a777e0e0c1e">
<img width="417" alt="image" src="https://github.com/gptscript-ai/gptscript/assets/11045408/5ebcabcf-e320-40dc-a45e-9b75c3df223f">

**Comment by cjellick** [comment]
cc @drpebcak

**Comment by drpebcak** [comment]
Hey @wmashal, the `GPTSCRIPT_PROVIDER_*` syntax is for accessing apis that already serve an openai compatible api, like mistral's la plateforme for example.

That being said, not pulling `GEMINI_API_KEY` from existing env for the gemini-aistudio-provider to use was an oversight. I have pushed changes to make that work now.

**Comment by drpebcak** [comment]
The other part of the issue related to `OPENAI_API_KEY` not being set seems to be a bug though - your first error says `cmd [/usr/bin/env python3 /root/.cache/gptscript/repos/bd6bbf89c7ecfd16d25c7d94dfc913b8c9e7c74a/python3.12/credential/credential.py]: exit status 1 2024/06/05 09:16:40 OPENAI_API_KEY is not set. 
` which implies it failed when the credential tool tried to call sys.prompt. That should not require an llm at all.

@wmashal what version of gptscript are you using?

**Comment by drpebcak** [comment]
The change I made was in the credential tool for the gemini-aistudio-provider, which is in a separate repo. That change has already been pushed: https://github.com/gptscript-ai/gemini-aistudio-provider/blob/main/credential/credential.py#L6

You can either set `GEMINI_API_KEY` in your env or enter it at the prompt when you run gptscript. Either way, you only need to do that once because it will be saved as a `gptscript credential` and loaded from the credential store after that.


The OPENAI_API_KEY issue you saw is still open.

**Comment by wmashal** [comment]
@drpebcak one more think the following error , I have python3 in another path why u set specific path in the tools.gpt 
https://github.com/gptscript-ai/gemini-aistudio-provider/blob/2a8dd073456fddac0c40c9a7f0e3c9193ff72713/credential/tool.gpt#L3 

**ERROR: /usr/bin/env: 'python3': No such file or directory : exit status 127**

**Comment by drpebcak** [comment]
That is a different problem altogether, but an interesting one for sure. Please open another issue for that error.

`/usr/bin/env python3` is the commonly accepted convention for a shebang - it will use the first version of python3 it finds on your path. In the case of gptscript, we vendor python for you so it should be using the version we install.

**Comment by wmashal** [comment]
@drpebcak issue opened 

https://github.com/gptscript-ai/gptscript/issues/533

**Comment by drpebcak** [comment]
I believe all the problems described here are either resolved or have other issues open for them now.
