### ISSUE TITLE
Handle the case when no gptscript is found more gracefully.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#467]
gptscript version v0.8.1+da33973d

**Steps to reproduce the problem**
1. Launch `gptscript --ui` from a directory that has no gptscript.

<img width="1288" alt="Screenshot 2024-06-10 at 12 01 27 PM" src="https://github.com/gptscript-ai/gptscript/assets/122560863/f81445f6-75d4-4100-837e-3d9c3e57d788">

2. On clicking the ">" , we are stuck in the following page

<img width="1266" alt="Screenshot 2024-06-10 at 12 02 22 PM" src="https://github.com/gptscript-ai/gptscript/assets/122560863/b00ff800-eba1-42c9-8749-5c77b8657846">

```
OUTPUT:

The service has been opened on port 10442.
 ✓ Compiled /api/file in 170ms (2284 modules)
 GET /api/file 404 in 210ms
 GET /api/file 404 in 3ms
 ○ Compiling /run ...
 ✓ Compiled /run in 1054ms (4992 modules)
 GET /run?file=error 200 in 1382ms
 ✓ Compiled /api/file/ÆnameÅ in 405ms (2677 modules)
 GET /api/file/error 404 in 555ms
 GET /api/file/error 404 in 4ms
```

**Comment by tylerslaton** [comment]
https://github.com/gptscript-ai/ui/commit/8161f658ced781c049a1a2e5bc56940d11ee7ea1

**Comment by sangee2004** [comment]
Tested with `GPTSCRIPT_CHAT_UI_TOOL=github.com/gptscript-ai/ui@v2` and this issue is addressed.
We get the following message now,
```
No scripts found
Create a new script in the folder you started the UI in to see it here!
```
