### ISSUE TITLE
Not able to execute scripts when tools get autolaunched at the beginning of chat session from UI

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#476]
**Steps to reproduce the problem:**
1. Launch UI using - ` GPTSCRIPT_CHAT_UI_TOOL=github.com/gptscript-ai/ui@v2 gptscript --ui `

2. Execute the following script that uses answers-from-the-internet tool 
```
tools: github.com/gptscript-ai/answers-from-the-internet
chat: true

You are a chatbot.
```

3. Script is stuck in executing state forever after selecting "Allow" for answers-from-the-internet tool

<img width="1231" alt="Screenshot 2024-06-10 at 4 18 32 PM" src="https://github.com/gptscript-ai/gptscript/assets/122560863/08da619f-2865-436c-a8f2-28fd800eb738">

**Comment by sangee2004** [comment]
This issue is seen only when there the tool gets autolaunched with some some random question. 

When I prevent the auto launch of the tool from happening by providing the following message in the tool body , then I am able to chat with this tool successfully.

```
You are a chatbot. Use your tools to answer the user's questions. When you start, just say hi and wait for the user to ask a question. Always include your sources in your answers.
```

**Comment by tylerslaton** [comment]
This is fixed by https://github.com/gptscript-ai/ui/commit/e43678f8e7e392d78de64f12f8f7b5cc4b8d82e4.

**Comment by sangee2004** [comment]
Tested with latest gptscript ui version from `main`

Able to execute the script provided in the issue successfully. User is prompted 2 times to trust the "
 answers-from-the-internet tool" tool since there are 2 tool calls being made by the LLM in this case.

```
<tool call> answersFromTheInternet -> {"question": "What is the capital of France?"} <tool call> answersFromTheInternet -> {"question": "What is the tallest mountain in the world?"}
```
