### ISSUE TITLE
"failed to load program: can not load tools path= name=testchat.gpt" error seen on launching chat after providing input parameters.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#489]
gptscript version v0.0.0-dev-7fc884c2-dirty

**Steps to reproduce the problem:**
1. Launch gptscript in UI mode using - `gptscript --ui --disable-cache`
2. Execute the following script

```
chat: true
description: This a search chatbot.
tools: github.com/gptscript-ai/search/duckduckgo
args: question: question to ask

search internet and provide answer for ${question}
```
3. Enter a question and start chat.

4. Following error is seen:
<img width="1051" alt="Screenshot 2024-06-12 at 4 02 20 PM" src="https://github.com/gptscript-ai/gptscript/assets/122560863/7cbab624-8503-4745-b45c-07320e56e404">

Console output when this error is seen:

```

 GET / 200 in 32ms
 GET /api/file 200 in 35ms
 GET /api/file 200 in 20ms
 GET /run?file=testchat 200 in 34ms
 POST /run?file=testchat 200 in 15ms
 POST /run?file=testchat 200 in 11ms
failed to load program: can not load tools path= name=testchat.gpt
```

**Comment by tylerslaton** [comment]
This is fixed by https://github.com/gptscript-ai/ui/commit/501541a5838e1648c4ad5147099560f4a3239284

**Comment by sangee2004** [comment]
Tested with latest gptscript ui.

This issue is not seen anymore. Able to execute the script successfully after entering the input parameter.
