### ISSUE TITLE
Intermittent error - " Something went wrong! Try again" encountered when executing scripts in UI.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#490]
gptscript version v0.0.0-dev-7fc884c2-dirty

**Steps to reproduce the problem:**
1. Launch gptscript in UI mode using - `gptscript --ui --disable-cache`
2. Execute the following script

```
chat: true
description: This a search chatbot.
tools: github.com/gptscript-ai/search/duckduckgo

You are a chatbot and can answer any question by searching the internet
```
3. Following error is seen sometimes
<img width="1286" alt="Screenshot 2024-06-12 at 4 39 29 PM" src="https://github.com/gptscript-ai/gptscript/assets/122560863/934cf4a1-11a5-4f43-a883-95cf408d8629">

This error goes away on page reload.

**Expected Behavior:**
This intermittent error should not be seen.

**Comment by njhale** [comment]
@sangee2004 I saw some related messages in our slack and it seems like this may have been resolved. Can you confirm if you still encounter this. Moving this over to `testing` for now.

**Comment by sangee2004** [comment]
I have not seen this issue happen for sometime now.
Closing this issue.
