### ISSUE TITLE
Use of "~" in `--workspace` option attempts to create invalid directory and fails. 

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#504]
gptscript version v0.8.2+1b5e068f

**Steps to reproduce the problem:**
1. Execute script with workspace having "~" - `gptscript --disable-cache --workspace=~/data  testimagevision.gpt`

This fails with following error
```
2024/06/14 16:28:26 mkdir /Users/sangeethahariharan/gptscript/~: not a directory
```

```
%pwd
/Users/sangeethahariharan/gptscript

 % gptscript --disable-cache --workspace=~/data  testimagevision.gpt
2024/06/14 16:28:26 mkdir /Users/sangeethahariharan/gptscript/~: not a directory

 % ls ~/data
browser_session		browser_session_no_js	cow.png			sunset.png		~
```

**Comment by g-linville** [comment]
@sangee2004 this should be fixed on main now.

**Comment by sangee2004** [comment]
Tested with gptscript version - `v0.0.0-dev-cb7fa1de-dirty`

This issue is not seen anymore.
