### ISSUE TITLE
failed to find a model provider for model [gpt-4o]

### ISSUE THREAD

**Issue by reselbob** [gptscript-ai/gptscript#508]
Hi:

I am a newbie. I installed GPTScript on Ubuntu.

```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

When I run the following command:

```
gptscript github.com/gptscript-ai/cli-demo
```

I get the following error: 

```
failed to find a model provider for model [gpt-4o]
```
I must be doing something really wrong, but I don't have a clue. Help?

**Comment by reselbob** [comment]
Turns out I had to buy some capacity on OpenAI

**Comment by reselbob** [comment]
There is no such thing as a free lunch!

**Comment by kamalbuilds** [comment]
Hey @reselbob , how to downgrade this to gpt-3.5 ?
