### ISSUE TITLE
Error executing GPT script

### ISSUE THREAD

**Issue by wmashal** [gptscript-ai/gptscript#533]
Hi 

I am facing the following error all the time when I am trying to use my OPENAI_API_KEY with the model gpt-4o 

Also when I run the command **gptscript credintial** , no credentials exists

Error executing GPT script: /usr/bin/env: 'python3': No such file or directory 11:30:56 failed to run tool [google-ai-studio-credential] cmd [/usr/bin/env python3 /root/.cache/gptscript/repos/3ba20cb1319a2a396a38f424123bbb8e5d32d352/credential/tool.gpt/python3.12/credential/credential.py]: exit status 127 2024/06/23 11:30:56 error, status code: 401, message: Incorrect API key provided: xx. You can find your API key at https://platform.openai.com/account/api-keys. failed to run credential tool github.com/gptscript-ai/gemini-aistudio-provider/credential: ERROR: /usr/bin/env: 'python3': No such file or directory : exit status 127

**Comment by wmashal** [comment]
@drpebcak is this issue still exist ?

**Comment by drpebcak** [comment]
I could not replicate it, so no.. I don't think so. If you can still get it to happen please add a comment with details on how you reproduced it.
