### ISSUE TITLE
Credential tool for github and slack related tools.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#545]
Github and Slack related tools relies on tokens being set as environment variables.

Tools - https://github.com/gptscript-ai/slack and https://github.com/gptscript-ai/slack-message
Environment variable - GPTSCRIPT_SLACK_TOKEN

Tools - https://github.com/gptscript-ai/query-github-issues , https://github.com/gptscript-ai/modify-github-issues and https://github.com/gptscript-ai/create-github-issues
Environment variable - GPTSCRIPT_GITHUB_TOKEN

We can have credential tools integrated with these tools so that users are prompted to enter the tokens.

**Comment by g-linville** [comment]
@sangee2004 I added credentials for these.

**Comment by sangee2004** [comment]
We now have `slackToken` and `githubToken` credentials being used for github and slack related tools.
