### ISSUE TITLE
Rate limited by github when trying to execute `digital-ocean-agent` with anthropic provider.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#576]
gptscript version - `v0.0.0-dev-51fd2b32-dirty`

**Steps to reproduce the problem:**
1. Execute  `digital-ocean-agent` with anthropic provider with `--disable-cache`  - `gptscript --default-model 'claude-3-5-sonnet-20240620 from github.com/gptscript-ai/claude3-anthropic-provider' --debug  --disable-cache github.com/gptscript-ai/digital-ocean-agen`

2. Rate limited by github and following error is reported:

`
2024/06/27 13:27:05 failed resolving ./databases.gpt from https://raw.githubusercontent.com/gptscript-ai/digital-ocean-agent/691fc6f31f061a5ecd78a2a9573c67f89c699c46/tool.gpt: failed resolving databases* from ./openapi.yaml from https://raw.githubusercontent.com/gptscript-ai/digital-ocean-agent/691fc6f31f061a5ecd78a2a9573c67f89c699c46/databases.gpt: failed resolving github.com/gptscript-ai/credential as api.digitalocean.combearer_auth with GPTSCRIPT_API_DIGITALOCEAN_COM_BEARER_AUTH as env and "Please provide a value for the GPTSCRIPT_API_DIGITALOCEAN_COM_BEARER_AUTH environment variable" as message and "bearer token" as field from https://raw.githubusercontent.com/gptscript-ai/digital-ocean-agent/691fc6f31f061a5ecd78a2a9573c67f89c699c46/openapi.yaml: failed to get GitHub commit of gptscript-ai/credential at HEAD (fallback error failed to find remote "https://github.com/gptscript-ai/credential.git" as "HEAD"): 403 Forbidden {"message":"API rate limit exceeded for 99.105.56.195. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
`

**Note ** - 
- This issue is not seen in my setup when executing the scripts without `--disable-cache` option.
- This issue is also seen when `GITHUB_AUTH_TOKEN` is set. But sometimes  I have seen this issue also not happen sometimes with  `GITHUB_AUTH_TOKEN` set.
- Digital Ocen agent works fine and does not hit this issue when testing with `gpt-4o` with or without `--disable-cache` option.

**Comment by g-linville** [comment]
@sangee2004 I merged changes that I think will fix this.

**Comment by sangee2004** [comment]
Tested with gptscript version - `v0.0.0-dev-a42c9e31-dirty`

Not hitting github rate limits when executing `github.com/gptscript-ai/digital-ocean-agent` with anthropic provider and using `--disable-cache` option.
