### ISSUE TITLE
UI - Changing workspace from UI does not take effect

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#579]
gptscript version - `v0.0.0-dev-51fd2b32-dirty`

**Steps to reproduce the problem**

1. Get k8s docs made available in local directory using git clone https://github.com/kubernetes/website.git
2. Run the following script to launch knowledge chat agent without workspace option - `gptscript --ui --disable-cache knowledge_remote.gpt `
```
tools: github.com/gptscript-ai/knowledge
context: github.com/gptscript-ai/context/workspace
chat: true

You are a helpful assistant that can retrieve information and answer questions using your tools. When you strat just introduce yourself and wait for the user to prompt you. 
You must use the knowledge tool to look up answers to your questions. Do NOT use the read tool. You may only answer questions with information you retrieve from the knowledge tool.
When you give answers, always give a proper citation to the best of your abilities.
```
3. Used UI to set  workspace parameter (edit existing value seen for workspace)  and set it to k8s doc directory from step1 . This resulted in UI prompting to restart the script and allow for this operartion.
4. Once script is loaded , tool calls made still continue to use the default workspace that was presented to me initially and I dont get any results for queries relating to k8s.

<img width="1472" alt="Screenshot 2024-06-27 at 1 55 49 PM" src="https://github.com/gptscript-ai/gptscript/assets/122560863/8d9e8386-215c-4ef5-9635-90d54e2a802e">
<img width="850" alt="Screenshot 2024-06-27 at 1 56 12 PM" src="https://github.com/gptscript-ai/gptscript/assets/122560863/e7d88593-f66c-4a57-90f1-b5a8bafd65c2">

**Comment by thedadams** [comment]
PR: https://github.com/gptscript-ai/gptscript/pull/575

**Comment by thedadams** [comment]
@sangee2004 The changes to fix this issue have been merged.

As state in Slack, you should be able to reproduce this issue (and then verify the fix) by doing something like
```sh
GPTSCRIPT_WORKSPACE_DIR=/some/other/path gptscript --workspace /my/workspace my-script.gpt
```
If the `my-script.gpt` uses the workspace context, then it will use `/some/other/path` instead of the `/my/workspace`, which is not correct.

**Comment by sangee2004** [comment]
Tested with gptscript version - `v0.0.0-dev-91751200-dirty`

Changing workspace from within UI works as expected.

User is not allowed to override the `workspace` by setting `GPTSCRIPT_WORKSPACE_DIR` anymore.
