### ISSUE TITLE
UI - Allowed to create a script with no instruction which does not load in UI (stuck in "loading your script.." state forever).

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#588]
gptscript version v0.0.0-dev-91751200-dirty

**Steps to reproduce the problem:**
1.  Use "Create a New script" option and create a new script by providing only File Name (Chat Bot Name can be provided or left empty). 
2. Once the script detail page is launched, notice that script cannot be loaded successfully and is stuck in "loading your script.." state forever .
<img width="1342" alt="Screenshot 2024-06-28 at 2 19 36 PM" src="https://github.com/gptscript-ai/gptscript/assets/122560863/1da69241-1357-48a0-afd6-5b8a0815dc2f">

In this case file is created with just `Chat: true`
3. Entering instruction in this page also does not get us out of this state
<img width="1325" alt="Screenshot 2024-06-28 at 2 24 12 PM" src="https://github.com/gptscript-ai/gptscript/assets/122560863/89f73c2a-eeee-4593-8702-81be7e6d760e">

Note - We are able to run this script from TUI.

**Comment by tylerslaton** [comment]
This is because GPTScript did not send a first message. I have now updated the logic to wait until the socket connects.

https://github.com/gptscript-ai/ui/commit/f6ebf796757e901e12a7f9a2cfdba73bc4624de7

**Comment by sangee2004** [comment]
Tested with latest `ui` build with gptscript version `v0.0.0-dev-a42c9e31-dirty` 

We are able to start with a script with just name provided now. User is provided with the following message and able to chat with LLMs.

<img width="652" alt="Screenshot 2024-07-01 at 9 06 49 AM" src="https://github.com/gptscript-ai/gptscript/assets/122560863/b5fe020d-f53e-4b06-b6c7-7c3b20522520">
