### ISSUE TITLE
UI - Accessing the source links displayed in chat responses , current UI context is lost.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#589]
**Steps to reproduce the problem:**
1. Execute the following script in UI
```
Name: MyBrowser
Description: MyBrowser tool for answering questions from internet
Tools: github.com/gptscript-ai/answers-from-the-internet
Chat: true

You are a chatbot. Use your tools to answer the user's questions. When you start, just say hi and wait for the user to ask a question. Always include your sources in your answers.
```
2.  Chat with this script
3. Click on the source link present in chat response.
4. Notice that the link will be opened in the current UI window  resulting in looking the current UI context.
5. Clicking on back from this page will take us back to script execution page were script is reloaded and conversation history is lost.

**Expected Behavior:**
Source link should be opened in a new browser session.

**Comment by tylerslaton** [comment]
This commit addresses this issue by making links open externally. Threads will solve the issue of reloading the page and no longer seeing past messages.

https://github.com/gptscript-ai/ui/commit/885d0a3b210f279e03acda0712c1110f4a7fc405

**Comment by sangee2004** [comment]
Tested with latest ui build with gptscript version `v0.0.0-dev-a42c9e31-dirty`

Clicking on the links in the source results in the link being opened in a new browser session.
