### ISSUE TITLE
UI - Use ".gpt" extension automatically for filename when creating gptscripts.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#591]
**Steps to reproduce the problem:**
1. Provide a file name with no extension when creating a script using ui.
2. User is forced to add ".gpt" extension to his file name.

<img width="845" alt="Screenshot 2024-06-28 at 3 32 07 PM" src="https://github.com/gptscript-ai/gptscript/assets/122560863/3967eba5-1f2e-42e1-8c40-f5c26d479a9e">

**Expected Behavior:**
".gpt" extension can  automatically be used for filename when creating gptscripts.

**Comment by sangee2004** [comment]
Similar issue is also seen when you trying to save with no filename provided.

<img width="798" alt="Screenshot 2024-07-11 at 11 27 23 AM" src="https://github.com/gptscript-ai/gptscript/assets/122560863/21ce3527-c9b0-43c1-9f63-1cb0362e47fe">

**Comment by njhale** [comment]
Going to close this out as this landing page is being removed soon.
