### ISSUE TITLE
UI - Launching remote script using `--ui` option with other providers does not launch the remote script .

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#597]
gptscript version v0.0.0-dev-37be71d1-dirty

**Steps to reproduce the problem**
1. Launch remote script using `--ui` option with other providers -
`gptscript --default-model 'claude-3-5-sonnet-20240620 from github.com/gptscript-ai/claude3-anthropic-provider' --workspace ~/local-files-demo/sample-data --ui --disable-cache github.com/gptscript-ai/local-files-demo`
2. This results in UI being launched with scripts listed from current directory were the UI was launched.
<img width="1292" alt="Screenshot 2024-07-01 at 2 56 22 PM" src="https://github.com/gptscript-ai/gptscript/assets/122560863/e762da21-2fb3-41ff-9418-1a6fb3c24abe">

**Expected Behavior:**

Should be able to launch the remote script .

**Note**
Able to launch the remote script by manually typing this -`/run?file=[github.com/gptscript-ai/local-files-demo](http://github.com/gptscript-ai/local-files-demo)` to the existing UI url.

**Comment by tylerslaton** [comment]
This should no longer be relevant since we're removing --ui. @sangee2004 Can you close this if nothing else is relevant here?

**Comment by sangee2004** [comment]
Closing this issue as "--ui" will not be supported in the near future and this workflow will not be supported in the electron app.
