### ISSUE TITLE
UI - Provide ability to create custom tools that are chat enabled.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#600]
gptscript version - `v0.0.0-dev-134dcde9-dirty`

**Steps to reproduce the problem:**
1. Launch gptscript using `--ui` option.
2. Use "Create a new scrip" option to create a new script.
 Notice that when adding Custom tools , they always get added without chat being enabled. 

**Expected Behavior:**
Provide ability to enable/disable chat when creating  Custom tools.  Also it  would be good  to make chat to be  set to`true`  by default.

**Comment by tylerslaton** [comment]
https://github.com/gptscript-ai/ui/pull/25

**Comment by sangee2004** [comment]
We have the ability to enable chat now when creating custom tools.

@tylerslaton Chat is not enable by default in the tools. Since the main tool is chat enabled by default (and cannot be changed), should we make the custom tools to have chat enabled as default ?

**Comment by tylerslaton** [comment]
> We have the ability to enable chat now when creating custom tools.
> 
> 
> 
> @tylerslaton Chat is not enable by default in the tools. Since the main tool is chat enabled by default (and cannot be changed), should we make the custom tools to have chat enabled as default ?

I don't think so. I'd consider the default state of a custom tool to be chat disabled. Is there reason you're thinking it should be the default?

**Comment by sangee2004** [comment]
@tylerslaton I understand that there is no real value in having  custom tool to be chat enabled by default.
Closing this issue.
