### ISSUE TITLE
Windows - `stream error: stream ID 1; INTERNAL_ERROR; received from peer`  error when trying to download node when using the TUI.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#615]
**Setup**- Windows VM  on Azure- Windows 11 Pro ( 8GB RAM , 2 vCPUs, Standard D2s v3) 

gptscript version -  v0.9.1+134dcde9

1. When trying to execute the following script that uses ` github.com/gptscript-ai/answers-from-the-internet` , i get an error -  `stream error: stream ID 1; INTERNAL_ERROR; received from peer`  when trying to download node.

```
tools: github.com/gptscript-ai/answers-from-the-internet
chat: true

You are a good assistant. Introduce yourself and wait for the user to ask you a question.
```

```
gptscript .\testinternet.gpt

  Hello! I'm here to help you with any questions or tasks you have. How can I assist you today?

> Who won 2024 superbowl?

    ┌────────────────────────────────────────────────────────────────────┐
    │ Call Arguments:                                                    │
    │                                                                    │
    │ answersFromTheInternet {"question":"Who won the 2024 Super Bowl?"} │
    └────────────────────────────────────────────────────────────────────┘

  Running answers-from-the-internet from github.com\gptscript-ai\answers-from-the-internet

    ┌───────────────────────┐
    │ Downloading Node 21.x │
    └───────────────────────┘
                             2024/07/08 18:18:50 stream error: stream ID 1; INTERNAL_ERROR; received from peer
```

Same issue is seen when I try to execute the script again.

I am able to get the tool to work directly - `gptscript github.com/gptscript-ai/answers-from-the-internet '{"question":"Who won the 2024 Super Bowl?"}'` 

Once this succeeds, then I am also able to get the chat script that uses the tool from step1 to work successfully.

**Comment by g-linville** [comment]
I'm gonna try this one

**Comment by sangee2004** [comment]
Tested on a new Windows VM.

I was not able to reproduce the issue reported with downloading of Node erroring out.
I was able to execute the script provided in the issue successfully.
