### ISSUE TITLE
UI - Current thread is not  highlighted in Dark mode

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#623]
gptscript version - `v0.0.0-dev-0c73f4b8-dirty`

**Steps to reproduce the problem:**
1. Launch UI - `gptscript --ui --workspace ./newthread --disable-cache`
2. Once UI is launched , execute any script.
3. Notice that a thread gets created automatically when we first with the script.
4. This thread does not get highlighted when in Dark mode. 

**Note** - We are able to see this highlighted as expected in the Light mode. 

Dark Mode ( no highlight for the current thread) 
<img width="1000" alt="Screenshot 2024-07-12 at 12 32 29 PM" src="https://github.com/user-attachments/assets/5a68af26-6706-40f1-a165-b018ea6ede93">

Light Mode (shows highlight for the current thread)

<img width="1059" alt="Screenshot 2024-07-12 at 12 33 39 PM" src="https://github.com/user-attachments/assets/23895c9c-4393-4f3f-8711-aadc52fefa3d">

**Comment by tylerslaton** [comment]
@sangee2004 I believe this is fixed. Please give it another look.

**Comment by sangee2004** [comment]
With the latest build, we see the current thread being highlighted



![Image](https://github.com/user-attachments/assets/0e463d41-c1c8-48ed-88ac-2c451dc5b406)
