### ISSUE TITLE
UI - Source links are not being shown in chat responses.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#624]
gptscript version - `v0.0.0-dev-0c73f4b8-dirty`

**Steps to reproduce the problem:**
1. Launch UI - `gptscript --ui --workspace ./newthread --disable-cache`
2. Once UI is launched , execute the following script  which asks for source to be returned.

```
Tools: github.com/gptscript-ai/answers-from-the-internet
Chat: true

You are a good assistant. Introduce yourself and wait for the user to ask you a question. Always include source of the search results in the response.
```

3. Source links are not shown in the chat responses. I see them being returned in the "Stack View" in `Messages` field.

<img width="667" alt="Screenshot 2024-07-12 at 12 21 41 PM" src="https://github.com/user-attachments/assets/b8871491-ee27-4133-a4f4-0204bacb30d9">

<img width="818" alt="Screenshot 2024-07-12 at 12 21 27 PM" src="https://github.com/user-attachments/assets/7367ed09-696e-486a-8cb6-73d5d59d64fe">

**Comment by tylerslaton** [comment]
@sangee2004 This is because the LLM is not deciding to show that content. Can you please add a part of your prompt that says "and show the source links"? I believe this will fix the issue for you.

**Comment by sangee2004** [comment]
Tested with electron app with commit - `c68bec95`

Able to see the source links presented in chat repsonse.


<img width="979" alt="Screenshot 2024-08-07 at 12 09 50 PM" src="https://github.com/user-attachments/assets/3d8b29f3-38a2-4b59-afa5-65a89f974abf">
