### ISSUE TITLE
UI - Options drop down on threads does not auto close after action is taken.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#627]
gptscript version - `v0.0.0-dev-0c73f4b8-dirty`

**Steps to reproduce the problem:**

1. Launch UI for remote script -`gptscript --ui --workspace ./newthread --disable-cache`
2. Initiate few chat threads
3. Delete one of the threads
4. Notice that the Options drop down on threads does not auto closed after action is taken and is presented for the next thread.

<img width="455" alt="Screenshot 2024-07-12 at 2 19 44 PM" src="https://github.com/user-attachments/assets/46e081ce-4b2c-4304-9313-72d596a4e82d">

After delete:

<img width="456" alt="Screenshot 2024-07-12 at 2 19 50 PM" src="https://github.com/user-attachments/assets/1888fb70-2369-4ab9-ae9d-374a53897adb">

**Comment by tylerslaton** [comment]
This should be fixed now @sangee2004!

**Comment by sangee2004** [comment]
This issue is addressed in the latest version of `ui` from `main`
