### ISSUE TITLE
UI - Provider set using `--default-model` when launching the UI is not used when executing scripts from within UI.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#636]
**Steps to reproduce the problem:**
1. Launch UI using `--default-model` option to use other providers (other than default model) - `gptscript --ui --disable-cache --default-model 'rubra-meta-llama-3-8b-instruct.Q8_0.gguf from http://localhost:1234/v1'`
2. Once UI is launched , execute any script.
3. Notice that user is prompted for openai credentials.

**Expected Behavior:**
Model used in `--default-model` when launching UI should be used when script execution is done.

**Comment by njhale** [comment]
This will be fixed in #635

**Comment by sangee2004** [comment]
Tested with gptscript version- `v0.0.0-dev-6e92ee7a-dirty`

1. Launched ui -  `gptscript --ui --disable-cache --default-model 'rubra-meta-llama-3-8b-instruct.Q8_0.gguf from http://localhost:1234/v1'`

2. Executed the following script from within ui
```
Tools: github.com/gptscript-ai/answers-from-the-internet, github.com/gptscript-ai/dalle-image-generation
Chat: true

You are a good assistant. Introduce yourself and wait for the user to ask you a question. Always include source of the search results in the response.
```

3.  I am prompted to enter the Openai Api keys after I type a chat message. I see the question - "which movie won best movie for 2024 oscar?" being processed by local models from the logs. 

<img width="1085" alt="Screenshot 2024-07-16 at 3 21 31 PM" src="https://github.com/user-attachments/assets/34758cba-cf8b-426d-bd73-009006af7b08">

**Comment by sangee2004** [comment]
Tested with gptscript version- v0.0.0-dev-6e92ee7a-dirty

Was able to verify that the fix works as expected without being prompted for openapi credentials when testing with other tools.
Example script that was used for testing which did not result in any prompting for openai keys.

```
Tools: github.com/gptscript-ai/search/brave
Chat: true

You are a chatbot. Say "Hi" and wait for user to ask you a question. Always return the source of  the search results.

```


There is a dependency on `gpt-3.5-turbo` model for `answers-from-internet` tool which resulted in the prompt for openai key which is as expected.

**Comment by Skybladev2** [comment]
@sangee2004 Can you please explain how to get  `from http://localhost:1234/v1` part of the parameter? How should I serve a local model properly?
