### ISSUE TITLE
UI - Error seen when chatting with threads that have workspace set.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#655]
gptscript version v0.0.0-dev-6d3043d4-dirty

**Steps to reproduce the problem:**
1. Launch ui.
2. Execute the following script from ui ( you can use any script that is chat enabled)
```
Tools: github.com/gptscript-ai/knowledge
Context: github.com/gptscript-ai/context/workspace
Chat: true

You are a helpful assistant that can retrieve information and answer questions using your tools. When you start just introduce yourself as Oracle and wait for the user to prompt you. 
You must use the knowledge tool to look up answers to your questions. Do NOT use the read tool. You may only answer questions with information you retrieve from the knowledge tool.
Even if you've seen the question before and have the answer in your context, don't reuse the answer - go back to the knowledge tool because it's possible the information it gave you previously is out of date.
When you give answers, always give a proper citation to the best of your abilities.
```
3. Use "+" option when in thread view to pick the same script (or any other script that is chat enabled) and launch it. (Notice that a new thread is already created at this point) 
4. Using manage workspace option, set workspace to a directory ( `/Users/sangeethahariharan/gptscript` in my case).
5. Restart script when prompted for it.
6. Notice that the following error message is seen
```
{"errno":-2,"code":"ENOENT","syscall":"open","path":"/Users/sangeethahariharan/gptscript/threads/btjov/state.json"}
```

<img width="1238" alt="Screenshot 2024-07-24 at 3 05 22 PM" src="https://github.com/user-attachments/assets/89af6305-cc2d-4d0b-9ce1-f95d3f7d290f">

**Comment by sangee2004** [comment]
With latest build from master , I am not able to reproduce the error mentioned in the bug when workspace is set to a directory that already exists. But I see the same error - `{"errno":-2,"code":"ENOENT","syscall":"open","path":"/Users/sangeethahariharan/gptscript/hello6/threads/j6em1p/state.json"}` when workspace is set to a directory that does not exists.

**Steps to reproduce the problem:**
1. Launch ui.
2. Execute any script
3. Change the workspace to a directory that does not exist.
4. Restart the script when user is prompted for it.

Script restart fails with the following error - `{"errno":-2,"code":"ENOENT","syscall":"open","path":"/Users/sangeethahariharan/gptscript/hello6/threads/j6em1p/state.json"}` 

Following this , if continue to chat , response is received after which we see the same error as above


<img width="900" alt="Screenshot 2024-07-23 at 3 48 32 PM" src="https://github.com/user-attachments/assets/25f4ed9f-3ee9-4967-b10b-435515116a1b">

**Comment by tylerslaton** [comment]
https://github.com/gptscript-ai/ui/pull/36

**Comment by sangee2004** [comment]
Tested with latest `ui` build from `master`

This issue is not seen any more.
Able to set `workspace` when launching script using "+"  and restart script successfully when prompted for it.
The error message reported in the issue is not seen anymore.
