### ISSUE TITLE
Thread history is lost when switching between threads.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#658]
gptscript version - `v0.0.0-dev-671f0f02-dirty`

**Steps to reproduce the problem:**
1. Launch `ui` - `gptscript --ui --disable-cache`
2. Start a thread by executing any script and make couple of chat conversations
3. Start a second thread and  make couple of chat conversations
4. Go back to thread from step 2  

Notice that there is no chat history.

**Expected Behavior:**
Chat history should be preserved across threads and be presented when switching between them.

**Comment by tylerslaton** [comment]
https://github.com/gptscript-ai/ui/pull/36

**Comment by sangee2004** [comment]
Tested with latest ui build from master.

Thread history is preserved when switching between threads.
