### ISSUE TITLE
UI - Not able to use some keys like up/down arrow/copy&paste on the terminal after quitting `gptscript --ui`.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#665]
gptscript version v0.0.0-dev-faaee653-dirty

**Steps to reproduce the problem:**
1. Launch ui - `gptscript --ui --disable-cache`
2. Once UI is launched successfully , use `^c` to quit the ui session.
3. After this notice that  some keys like up/down arrow/copy&paste on the terminal stop working properly.

It starts working as expected once we `clear` the terminal.

**Comment by tylerslaton** [comment]
`--ui` is removed so can close this, right @sangee2004?

**Comment by sangee2004** [comment]
Closing this issue.
