### ISSUE TITLE
Issues seen when using `^c` to terminate a chat message.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#666]
gptscript version v0.0.0-dev-faaee653-dirty

**Scenario 1:**
Takes very long (about 20 -25 secs) to get interrupted message and user prompt when cancelling a chat message
Also we loose the actual user prompt and exec call that was made after this.

**Steps to reproduce the problem**
1. Execute the following script
```
Context: github.com/gptscript-ai/clio/context
Chat: true

You are a good assistant. Wait for user to ask you a question.
```
3. I tried to list all files from a directory that was taking long.
4. When listing of files is still in progress, use  `^c` to terminate a chat message. 

Notice that it takes very long (about 20 -25 secs) to get the interrupted message and user prompt after cancelling a chat message
Also we loose the actual user prompt and exec call that was made.

```
gptscript chat.gpt

  Hey there! What DevOps task do you need help with today?                                                                                                                                   

Interrupted

>  
```

**Expected Behavior:**
1. Should be able to see the interrupted the message and prompt right after a chat message canceled.
2. It would be good to still show the user prompt and tool call in the thread .

**Scenario 2:**
Using  `^c` to terminate a chat message 2nd time causes the script to exit.

1. Execute the following script
```
Context: github.com/gptscript-ai/clio/context
Chat: true

You are a good assistant. Wait for user to ask you a question.
```
3. Tried to list all files from a directory that was taking a long time.
4. When listing of files is still in progress, use  `^c` to terminate a chat message. 
5.  Tried to again list all files from a directory that was taking a long time.
6. When listing of files is still in progress, use  `^c` to terminate a chat message. 

Notice that the script exits in this case.

**Expected Behavior:**
Only the chat message should be terminated in the case and user should still be able to continue to chat.

**Comment by sangee2004** [comment]
Tested with gptscript version - `v0.0.0-dev-c8cf3106-dirty`

I am able to reproduce this issue when testing this version.

**Comment by sangee2004** [comment]
Tested with gptscript version v0.0.0-dev-24b1f24e-dirty

I am now not able to reproduce `scenario 2`  any more.

I tried to list files and did a `^c` when files were being listed . Repeated this 4 times and I still continue to be the chat session as expected 

```
gptscript chat.gpt

  Hello! How can I assist you today? If you have any DevOps-related tasks or need help with CLI commands, feel free to let me know!    

Interrupted

Interrupted

Interrupted

Interrupted

>  
```


But `scenario 1` is still happening were I loose the prompt (and the contents that were displayed before `^c` was hit).

**Comment by ibuildthecloud** [comment]
We delete the old prompt and content because they aren't available to the session anymore, they are forgotten. I just felt if I left them on the screen people would think they could enter a new prompt and the LLM would know about the content on the screen from the canceled run, which is not the case.
