### ISSUE TITLE
Openapi tool - Do not prompt users to confirm for `listOperationsDigitaloceanApi` and `getSchemaDigitaloceanApi` calls

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#702]
gptscript version v0.0.0-dev-c8cf3106-dirty

**Steps to reproduce the problem:**
**PreReq** - set following variables

```
export GPTSCRIPT_OPENAPI_REVAMP=true
export GPTSCRIPT_API_DIGITALOCEAN_COM_BEARER_AUTH=***
```

1. Execute the following DO agent openapi tool 
```
tools: https://raw.githubusercontent.com/gptscript-ai/digital-ocean-agent/main/openapi.yaml
Chat: true

You are a good assistant .Wait for user to ask you a question.
```
2. Ask it to list all droplets

Notice that you will be promoted for  allowing the following calls:
listOperationsDigitaloceanApi{}
getSchemaDigitaloceanApi{} 
runOperationDigitaloceanApi {"operation":"droplets_list","args":"{}"} 

**Expected Behavior:**
There should be no need for asking users to confirm for listOperationsDigitaloceanApi{} and getSchemaDigitaloceanApi{} .

Also the output for listOperationsDigitaloceanApi{} is very large.

**Comment by g-linville** [comment]
^ PR for this is ready. Will move to Testing once it's merged.

**Comment by g-linville** [comment]
Merged and ready for testing.

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with latest version of gptscript.
