### ISSUE TITLE
UI - DISABLE_CACHE=true is required when launching UI for changes made to the assistant to take effect

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#713]
gptscript version v0.0.0-dev+160a7334

**Steps to reproduce the problem:**
1. Launch UI -  `GATEWAY_URL=https://gateway-api.gptscript.ai gptscript --ui --disable-cache`
2. Create an assistant.
3. Edit this assistant and add a tool.
4. Restating the script or running the script from Home page does not result in changes being picked unless DISABLE_CACHE=true is used when launching UI.

**Comment by tylerslaton** [comment]
This should be fixed, please give it another look @sangee2004

**Comment by sangee2004** [comment]
This issue is not seen when testing with  commit id - `c5e7e2937`
