### ISSUE TITLE
UI - Not able to run assistant that has answersFromInternet tool.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#714]
gptscript version v0.0.0-dev+160a7334

**Steps to reproduce the problem:**
1. Make sure the cache for gptscript is cleared - `~/Library/Caches/gptscript`.
2. Launch UI -  `DISABLE_CACHE=true GATEWAY_URL=https://gateway-api.gptscript.ai gptscript --ui --disable-cache`
3. Run an assistant that has answersFromInternet tool.
4. Ask any question.
5. After allowing the tool call for `answersFromInternet` , we are not able to fetch any information from the tool 
Following error is seen when tool call is made:

<img width="584" alt="Screenshot 2024-08-06 at 8 47 02 AM" src="https://github.com/user-attachments/assets/6ad792f1-d5b4-41af-a5b4-99816f538aec">

**Comment by tylerslaton** [comment]
@sangee2004 Do you still see this?

**Comment by sangee2004** [comment]
This issue is not seen anymore.
