### ISSUE TITLE
UI - Explore view flashes for a second before “My Assistants” view is presented on UI launch.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#715]
gptscript version v0.0.0-dev+160a7334

**Steps to reproduce the problem:**
1. Launch UI -  `DISABLE_CACHE=true GATEWAY_URL=https://gateway-api.gptscript.ai gptscript --ui --disable-cache`
2. Notice that the Explore view flashes for a second before “My Assistants” view is presented .

**Comment by tylerslaton** [comment]
This screen is completely overhauled. Can you give it another look? @sangee2004

**Comment by sangee2004** [comment]
When Electron app is launched now , we are taken to the `chat` view.
When accessing `build` , ` My Assistants` view is presented and there is no glitch .
Closing this issue.
