### ISSUE TITLE
UI- `Instruction Type` and `code` for tools gets reset to `Prompt` and `Instrutions` in edit view.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#717]
gptscript version v0.0.0-dev+160a7334

**Steps to reproduce the problem:**
1. Launch UI -  `DISABLE_CACHE=true GATEWAY_URL=https://gateway-api.gptscript.ai gptscript --ui --disable-cache`
2. While creating a script ,add a tool with Instruction Type set to “code” and code set to type “shell”.
3. Edit this script and edit the tool.
4. Notice that the Instruction Type and code for tools gets reset to “Prompt” and “Instructions” in edit view.

Edit view for a tool that was created Instruction Type set to “code” and code set to type “shell”.

<img width="627" alt="Screenshot 2024-08-06 at 9 02 20 AM" src="https://github.com/user-attachments/assets/3875670b-a0c6-454c-b8c7-8d03aade03d7">

**Comment by tylerslaton** [comment]
This is fixed by this commit.

https://github.com/gptscript-ai/ui/commit/11f69ab8386c42cfa15fc52c1fa840cadbf34f11

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with  commit id `6e2f8ed99`
