### ISSUE TITLE
UI - No easy way to add system tools

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#718]
gptscript version v0.0.0-dev+160a7334

**Steps to reproduce the problem:**
1. Launch UI -  `DISABLE_CACHE=true GATEWAY_URL=https://gateway-api.gptscript.ai gptscript --ui --disable-cache`
2. Try to create an assistant which uses system tools.
If i need to add a system tool say `sys.exec` , I have to use `Find more tools` option and then use `Add by URL` were i type the system tool name.

There should be a better way to discover and add system tools.

**Comment by tylerslaton** [comment]
@sangee2004 This should be addressed now.

**Comment by sangee2004** [comment]
With latest version of electron app (commit id `c5e7e29371`) , we are able to add system tools using "Find Tools" option. They are listed in "System Tools" section in the "Tool catalog"
