### ISSUE TITLE
UI - There is no visual indication when tool gets added using`Add by URL` option.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#720]
gptscript version v0.0.0-dev+160a7334

**Steps to reproduce the problem:**
1. Launch UI -  `DISABLE_CACHE=true GATEWAY_URL=https://gateway-api.gptscript.ai gptscript --ui --disable-cache`
2. Create an assistant.
3. Edit the assistant and tools by using "Find more tools" option.
4. Use "Add by URL" option to add any remote/system tool.
5. Once the "+" button is used , notice that the tool that was entered gets cleared and there is no way to 

<img width="419" alt="Screenshot 2024-08-06 at 9 17 17 AM" src="https://github.com/user-attachments/assets/ea4f12bf-bc19-4d23-b14f-387883cb36b2">

After using "+" to ad the tool

<img width="402" alt="Screenshot 2024-08-06 at 9 17 23 AM" src="https://github.com/user-attachments/assets/b85018a3-3744-4c95-b252-a14b8595db08">

Note - Once i close this window, I do see the tool being added to the assistant.

**Comment by sangee2004** [comment]
The tool actually gets added to the bottom of the Tool Catalog list which is not really giving any feedback to the user that it was actually added.

**Comment by tylerslaton** [comment]
The new UX should address this, can you check again?

**Comment by sangee2004** [comment]
Tested with electron buid - `c5e7e293`

We now have the visual indication about the tool that gets added


![Image](https://github.com/user-attachments/assets/9532afb3-6a48-4038-97c2-c8b9d2ad5460)
