### ISSUE TITLE
UI - Provide user an indication when token expires instead of making all the data disappear without any notication.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#721]
gptscript version v0.0.0-dev+160a7334

**Steps to reproduce the problem:**
1. Launch UI -  `DISABLE_CACHE=true GATEWAY_URL=https://gateway-api.gptscript.ai gptscript --ui --disable-cache`
2. UI was functional for me.
3. Wait for Token to expire
4. On Token expiry,  `My Assistants` shows  no assistants (that i had created previously ) and the `Explore` page shows no assistants (used to show 11 assistants including 4 of mine). I also see myself as "undefined" in profile.
<img width="288" alt="Screenshot 2024-08-06 at 9 25 34 AM" src="https://github.com/user-attachments/assets/76597d1a-ee26-431b-901a-c5c057f17dac">

**Expected Behavior:**
User should be notified of token expiry in this case should be forced to login.

**Comment by tylerslaton** [comment]
This approach is overhauled please give it another look. @sangee2004

**Comment by sangee2004** [comment]
This issue is not relevant anymore with the new approach.
