### ISSUE TITLE
UI - Explore - Need to do multiple reloads to fetch all the assistants in `Explore` view (each `load more` fetches only 2 assistants)

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#725]
gptscript version v0.0.0-dev+b77cd130

**Steps to reproduce the problem:**
1. Launch UI.
2. Make sure you have many assistants that can be listed. In my case there are 17 assistants.
3. Go to Explorer
4. There are 10 assistants that are listed as expected.
5. Use "load More" to fetch the next set of assistants.
Only 2 more assistants get fetched.
I had to do "load More" multiple times to get all 17 assistants.

**Expected Behavior:**
 "load More" should fetch all the next 10 assistants.

**Comment by tylerslaton** [comment]
This should be fixed now.

**Comment by sangee2004** [comment]
This issue is fixed when testing with builds from commit -id `c5e7e2937`

"load More" should fetch all next 10 assistants as expected.
