### ISSUE TITLE
Show the tokens counts to better understand the cost

### ISSUE THREAD

**Issue by kaihendry** [gptscript-ai/gptscript#73]
Since gptscript goes back forth with the OPENAI_API_KEY, it would be nice to get some indication of its cost. 

I believe this is expressed in tokens, so ideally .usage.total_tokens are shown from the responses & at a stretch maybe show the tokens of they [query](https://platform.openai.com/tokenizer) itself.

That said, I am not sure if the tokenizer is accurate: how https://community.openai.com/t/estimating-cost-of-a-query/651131

**Comment by njhale** [comment]
Sorry for the delay in getting back to you @kaihendry! This was on our radar for a while and we exposed the total token counts from chat completion streams soon after they were implemented by OpenAI.

```
gptscript examples/bob-as-shell.gpt
...
02:01:50 ended    [main] [output=Bob said: \"Thanks for asking How are you doing?, I'm doing great fellow friendly AI tool!\"]
02:01:50 usage    [total=201] [prompt=180] [completion=21]
...
```

I think this should satisfy the request for a way to track cost, so I'm closing this out.

**Comment by kaihendry** [comment]
Thanks for the followup! Not sure why my token count is so different to yours? https://gist.github.com/kaihendry/aab648349d03b2ec1139ea96514572dd
