### ISSUE TITLE
UI - Not able to run assistants after the agent name is edited. Need to do a "Restart script" for it succeed every time it is run.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#732]
Electron app build wit commit id- `4414471`

**Steps to reproduce the problem:**
1. Lauch electron app using `npm run dev:electron`
2. Create an assistant.
3. Edit the assistant from `Home` page and change the agent name.
4. Come back to `Home` page and run this assistant.

Following error is seen:

<img width="1006" alt="Screenshot 2024-08-06 at 3 50 58 PM" src="https://github.com/user-attachments/assets/b8f95d61-e70d-47b7-8097-57db1166f869">

Using "Restart Script" gets us out of this error and able to see the script load successfully.

5. Again go to `Home` page and run this assistant.
The same load error will be seen and we can recover only using Restart Script" option.

**Note** - I have not seen this issue when testing the same workflow using "--ui" option.

**Comment by tylerslaton** [comment]
This should be fixed now.

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing wit builds from commit id - `3787f27`
