### ISSUE TITLE
Credentials need to support multiple instances of the same provider.

### ISSUE THREAD

**Issue by cloudnautique** [gptscript-ai/gptscript#804]
Take for example the situation where a tool connects to a Database. The credentials are defined in that tool with a static name like db.password. 

This creates a problem because it prevents a user from having two tools that both connect to the same type of database with different credentials. This won't work if there is 1 database host with two separate DB users for different access. It also prevents two separate db servers with different credentials. 

Also, somewhat related to this is that you might have different environments, and not want to accidentally use a prod db instead of the development credentials.

**Comment by g-linville** [comment]
This can be handled through credential aliases, contexts, and overrides. Closing this out.
