### ISSUE TITLE
Add test CI

### ISSUE THREAD

**Issue by tylerslaton** [gptscript-ai/gptscript#82]
We'll want to have an integration and unit test suite to validate quality between changes. Minimally we should run tests to make sure that the examples in our repo work as we expect.

**Comment by kaihendry** [comment]
Something like https://github.com/kaihendry/gptscript-test/blob/main/.github/workflows/run.yml ?

**Comment by njhale** [comment]
Closing this out as we now have a suite of unit, smoke, and e2e tests that run on PRs and merge to main.
