### ISSUE TITLE
gptscript 443

### ISSUE THREAD

**Issue by wendy2017** [gptscript-ai/gptscript#904]
when i use using storybook.gpt,it shows errors bellow::
tips: in asia,using vpn 
api.openai.com/v1/chat/completions": dial tcp 103.252.115.221:443: connect: connection refused

anybodys can help? please

**Comment by njhale** [comment]
It's been a while since I responded to this issue. It seems to be related to OpenAI's region-locking and is likely not something we can address on our side. I'm going to close this out.
