### ISSUE TITLE
Not able to run some example scripts which use relative file path to `gptscript` from `examples` directory.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#94]
**Steps to reproduce the problem:**

1. Launch debug UI using the following steps mentioned in the `Quisckstart` section in ReadMe.
```
git clone https://github.com/gptscript-ai/gptscript
cd gptscript/examples

# Run the debugging UI
gptscript --server
```

Using Gptscript UI , we are not able to run some scripts like - `samples-readme.gpt` , `syntax-from-code.gpt`  , `describe-code.gpt` because of these scripts  using relative path to `gptscript`  like `pkg/parser/parser.go` . The working directory for UI is `/examples` dir but scripts uses `gptscript` as  the working directory.

```
examples % gptscript syntax-from-code.gpt                                           
11:36:45 started  [main]
11:36:45 sent     [main]
11:36:45 started  [sys.read(2)] [input={"filename":"pkg/parser/parser.go"}]
11:36:45 sent     [sys.read(2)]
2024/02/29 11:36:45 open pkg/parser/parser.go: no such file or directory
```
The same script will work fine when invoked from `gptscript` dir:
`gptscript % gptscript --cache=false examples/syntax-from-code.gpt`

Should the example scripts in this case be modified to using paths relative to the directory were the scripts are residing (instead of being relative to `gptscript` ) ? Or We could also instruct users to launch  `gptscript --server` from `gptscript` directory to get around this problem.

**Expected Behavior:**
We should be able to provide a relative file paths in the gptscripts (relative from the current working directory of the scripts) and expect it to work when executed from any directory.

**Comment by cjellick** [comment]
debug UI has gone away. closing
